### ISSUE TITLE
Only saves one delete contact

### ISSUE THREAD

**Issue by rtysmith** [danielgalasko/app-contactcleanse#1]
Hi Daniel,

I updated the app to the paid version, but it is only storing one contact in the trash can?

**Comment by danielgalasko** [comment]
I’m so sorry to hear this, for reference to others, I have suggested deleting the App.

Another suggestion could be to try tapping “reset” and giving it another go

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
