### ISSUE TITLE
Only one contact in trash

### ISSUE THREAD

**Issue by rtysmith** [danielgalasko/app-contactcleanse#2]
Hi - just updating from email - but you are correct in that I upgraded to the full version but will only list one swipe left in the delete folder.

FYI - I've moved to Cinder as its been awhile - love the concept but Cinder has now copied you and working...

Still like your solution!

**Comment by danielgalasko** [comment]
Appreciate the support anyhow.

Would love to know what was broken though 🤔 I suspect it could be where your contacts are actually stored on your device.

Would you know if your contacts are mostly from Google, Microsoft Exchange or something like that?
